# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            That Mike Flynn
tagline:          "Projects and apps from someone that likes to use his programming powers on fun stuff."
description:      'A showcase of my projects and apps.'
url:              https://thatmikeflynn.com
baseurl:          /

author:
  name:           'Mike Flynn'
  url:            https://twitter.com/thatmikeflynn

paginate:         5

# Custom vars
version:          2.1.0

# Gems
gems:
  - jekyll-sitemap
  - jekyll-paginate
